/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Entidades.Contactos;
import java.util.TreeMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Netbook
 */
public class vistaBuscar extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel() ;
    
    /**
     * Creates new form vistaBuscar
     */
    public vistaBuscar() {

        initComponents();
        iniciarTabla();
        cargarDatos(VistaPrincipal.direc.getDirectorio());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDirectorio = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbFiltrar = new javax.swing.JMenu();
        miFiltrarPorCiudad = new javax.swing.JMenuItem();
        miTelefono = new javax.swing.JMenuItem();
        mbSalir = new javax.swing.JMenu();

        setTitle("Directorio");

        jDesktopPane1.setBackground(new java.awt.Color(102, 255, 255));

        tablaDirectorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDirectorio);

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        mbFiltrar.setText("Filtrar");

        miFiltrarPorCiudad.setText("Filtrar por Ciudad");
        mbFiltrar.add(miFiltrarPorCiudad);

        miTelefono.setText("Filtrar por Telefono");
        mbFiltrar.add(miTelefono);

        jMenuBar1.add(mbFiltrar);

        mbSalir.setText("Salir");
        mbSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mbSalirMouseClicked(evt);
            }
        });
        mbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(mbSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbSalirActionPerformed
        // minimiza la ventana

    }//GEN-LAST:event_mbSalirActionPerformed

    private void mbSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mbSalirMouseClicked
        // esconde la ventana
        hide();

    }//GEN-LAST:event_mbSalirMouseClicked

    public void iniciarTabla() {

        modelo.addColumn("Dni");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Direccion");
        modelo.addColumn("Ciudad");
        modelo.addColumn("Telefono");
        tablaDirectorio.setModel(modelo);
        

    }
    

    public void cargarDatos(TreeMap p) {
        Object[] datos = new Object[modelo.getColumnCount()];
        int i = 1;
        for (Object r : p.values()) {
            Contactos c = (Contactos) r;
        modelo.addRow(new Object[]{c.getDni(), c.getNombre(), c.getApellido(), c.getDireccion(), c.getCiudad(), c.getTelefono()});
        }
    
        
    
            
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mbFiltrar;
    private javax.swing.JMenu mbSalir;
    private javax.swing.JMenuItem miFiltrarPorCiudad;
    private javax.swing.JMenuItem miTelefono;
    private javax.swing.JTable tablaDirectorio;
    // End of variables declaration//GEN-END:variables
}
